include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_RGNANO_SIM \
	-DCPP_MEMORY \
	-D_DEBUG \
	-DDEBUG

TOOLPATH=/mingw32/bin
PREFIX :=

# Same optimisation and 32-bit SSE floats as the device (-O3, not x87),
# so optimiser- and float-dependent bugs show up here too
CFLAGS	:= -mthreads -g -O3 -msse2 -mfpmath=sse -Wall $(INCLUDES) $(DEFINES) -I$(PWD)/../sources -I$(PWD)/../sources/Externals
CXXFLAGS:= $(CFLAGS) -std=gnu++03
# GUI subsystem: never opens a console window (which would steal focus)
LDFLAGS := -L../../libs/Wsdl-mingw -mwindows
LIBS     :=  -lmingw32 -lSDL -luser32 -lgdi32 -lwinmm -ldxguid
OUTPUT   := ../lgpt-rgnano-sim
EXTENSION:= exe
