#!/usr/bin/env python3
"""Play a demo song in the simulator, stop it, and measure what keeps sounding.

Catches two classes of audio bug agents cannot hear:
- sound that keeps going after Stop (hung voices, runaway effect tails)
- a noise floor that creeps up the longer a song plays

It loads the demo through AUTO_LOAD_LAST, presses Start on the Song screen,
waits, presses Start again to stop, keeps capturing, and prints:
- loudness per 5 s while playing, plus the quietest 100 ms in each window
  (the noise floor: it should not rise over time)
- loudness per 0.5 s after Stop (should fall to silence within the FX tail)

Usage:
    python tools/audio_stop_probe.py --demo lgpt_NeonDrive --play 120 --after 12
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
PROJECTS = ROOT / "projects"
SIM_TRACKS = ROOT / "rgnano-sim-data" / "tracks"
DEMOS = PROJECTS / "resources" / "demos"
LOG = PROJECTS / "rgnano-sim.log"
NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)

sys.path.insert(0, str(TOOLS))
import audio_report  # noqa: E402


def run_probe(demo: str, play_s: float, after_s: float, capture: Path) -> None:
    src = DEMOS / demo
    dst = SIM_TRACKS / demo
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    last = PROJECTS / "last_project"
    saved = last.read_text() if last.exists() else None
    last.write_text(f"./rgnano-sim-data/tracks/{demo}")

    script = PROJECTS / "rgnano-sim-stop-probe.rgsim"
    script.write_text("\n".join([
        f"# generated by tools/audio_stop_probe.py for {demo}",
        "wait 1500",
        "expect_view song",
        f"start_audio_capture {capture.name}",
        "press s 80",
        f"wait {int(play_s * 1000)}",
        "press s 80",
        f"wait {int(after_s * 1000)}",
        "end_audio_capture",
        "quit",
    ]) + "\n")
    res_dir = PROJECTS / "resources" / "RGNANO_SIM"
    shutil.copy(res_dir / "config.xml", PROJECTS / "config.xml")
    shutil.copy(res_dir / "mapping.xml", PROJECTS / "mapping.xml")
    env = os.environ.copy()
    env["PATH"] = "C:\\msys64\\mingw32\\bin;" + env.get("PATH", "")
    cmd = [str(PROJECTS / "lgpt-rgnano-sim.exe"), f"-RGNANOSIM_SCRIPT={script}", f"-RGNANOSIM_LOG={LOG}",
           "-RGNANOSIM_HEADLESS=YES", "-RGNANOSIM_MUTE=YES"]
    try:
        subprocess.run(cmd, creationflags=NO_WINDOW, cwd=ROOT, env=env,
                       timeout=play_s + after_s + 120)
    finally:
        script.unlink(missing_ok=True)
        if saved is None:
            last.unlink(missing_ok=True)
        else:
            last.write_text(saved)


def find_capture(name: str) -> Path:
    for base in (ROOT, PROJECTS):
        p = base / name
        if p.exists():
            return p
    raise SystemExit(f"capture {name} not found (see {LOG})")


def report(wav: Path, play_s: float) -> dict:
    data, rate = audio_report.read_wav(wav)
    mono = data.mean(axis=1)
    stop = int((play_s + 0.1) * rate)
    playing, after = mono[:stop], mono[stop:]

    def rms(x: np.ndarray) -> float:
        return float(np.sqrt(np.mean(x ** 2))) if len(x) else 0.0

    print(f"capture {wav.name}: {len(mono) / rate:.1f}s")
    print("while playing (5 s windows): loudness / quietest 100 ms (noise floor)")
    floors = []
    win, small = 5 * rate, rate // 10
    for i in range(0, len(playing) - win + 1, win):
        seg = playing[i:i + win]
        q = min(rms(seg[j:j + small]) for j in range(0, len(seg) - small + 1, small))
        floors.append(q)
        print(f"  {i / rate:6.1f}s  {audio_report.db(rms(seg)):6.1f} dB   floor {audio_report.db(q):6.1f} dB")
    print("after Stop (0.5 s windows):")
    tail = []
    half = rate // 2
    for i in range(0, len(after) - half + 1, half):
        level = audio_report.db(rms(after[i:i + half]))
        tail.append(level)
        print(f"  +{i / rate:4.1f}s  {level:6.1f} dB")
    return {"floors_db": [audio_report.db(f) for f in floors], "after_db": tail}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--demo", default="lgpt_NeonDrive")
    ap.add_argument("--play", type=float, default=60.0, help="seconds to play before Stop")
    ap.add_argument("--after", type=float, default=10.0, help="seconds to keep capturing after Stop")
    ap.add_argument("--keep", action="store_true", help="keep the capture WAV")
    args = ap.parse_args()
    name = f"stop-probe-{args.demo}.wav"
    run_probe(args.demo, args.play, args.after, Path(name))
    wav = find_capture(name)
    result = report(wav, args.play)
    if not args.keep:
        wav.unlink()
    late = result["after_db"][-4:]
    ok = all(level < -70 for level in late)
    print("after-stop silence:", "OK" if ok else "STILL SOUNDING")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
