#!/usr/bin/env python3
"""Build the demo songs, bounce them through the real app, and audit the audio.

For each tools/demos/*.py song this:
1. writes the lgpt_<Name> project (projects/resources/demos + simulator tracks)
2. points the simulator's last_project at it (AUTO_LOAD_LAST)
3. runs a generated script: Project -> Render: Stereo -> Start -> Stop
4. copies the app's own mixdown.wav into the artifacts folder, trimmed to one
   pass of the song, and writes an audio report (+ spectrogram PNG)

Usage:
    python tools/render_demos.py                 # all demos
    python tools/render_demos.py --only neon_drive
    python tools/render_demos.py --no-build      # reuse the simulator build
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import wave
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
PROJECTS = ROOT / "projects"
SIM_TRACKS = ROOT / "rgnano-sim-data" / "tracks"
DEMO_OUT = PROJECTS / "resources" / "demos"

sys.path.insert(0, str(TOOLS))
import audio_report  # noqa: E402
import lgpt_composer  # noqa: E402


def build_sim() -> None:
    subprocess.run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
                    str(TOOLS / "build-rgnano-sim.ps1")], cwd=ROOT, check=True)


def trim_wav(src: Path, dst: Path, seconds: float) -> None:
    with wave.open(str(src), "rb") as r:
        params = r.getparams()
        frames = min(r.getnframes(), int(seconds * params.framerate))
        data = r.readframes(frames)
    with wave.open(str(dst), "wb") as w:
        w.setparams(params)
        w.writeframes(data)


def render(name: str, project: lgpt_composer.Project, artifacts: Path, tail: float,
           audible: bool = False) -> dict:
    folder = project.save(DEMO_OUT)
    sim_folder = SIM_TRACKS / folder.name
    if sim_folder.exists():
        shutil.rmtree(sim_folder)
    shutil.copytree(folder, sim_folder)
    mixdown = sim_folder / "mixdown.wav"
    if mixdown.exists():
        mixdown.unlink()

    (PROJECTS / "last_project").write_text(f"./rgnano-sim-data/tracks/{folder.name}")

    seconds = project.length_seconds()
    # The Stereo render streams in real time; wait for one full pass plus the
    # tail, extra audio is trimmed afterwards.
    wait_ms = int(seconds * 1000 + tail * 1000 + 1500)
    script = PROJECTS / "rgnano-sim-demo-render.rgsim"
    script.write_text("\n".join([
        f"# generated by tools/render_demos.py for {name}",
        "wait 1500",
        "expect_view song",
        "route song.to_project",
        "expect_view project",
        "sim_set_render_mode 1",
        "press s 80",
        f"wait {wait_ms}",
        "press s 80",
        "wait 600",
        "expect_project_file_bytes mixdown.wav 100000",
        "sim_set_render_mode 0",
        "expect_no_error",
        "quit",
    ]) + "\n")

    exe = PROJECTS / "lgpt-rgnano-sim.exe"
    res_dir = PROJECTS / "resources" / "RGNANO_SIM"
    shutil.copy(res_dir / "config.xml", PROJECTS / "config.xml")
    shutil.copy(res_dir / "mapping.xml", PROJECTS / "mapping.xml")
    log = PROJECTS / "rgnano-sim.log"
    env = os.environ.copy()
    env["SDL_VIDEODRIVER"] = "dummy"  # headless: no window, no focus stealing
    env["PATH"] = "C:\\msys64\\mingw32\\bin;" + env.get("PATH", "")
    cmd = [str(exe), f"-RGNANOSIM_SCRIPT={script}", f"-RGNANOSIM_LOG={log}"]
    if not audible:
        cmd.append("-RGNANOSIM_MUTE=YES")
    proc = subprocess.run(cmd,
                          cwd=ROOT, env=env, timeout=wait_ms / 1000 + 120)
    script.unlink(missing_ok=True)
    if proc.returncode != 0 or not mixdown.exists():
        raise RuntimeError(f"{name}: render failed (exit {proc.returncode}); see {log}")

    artifacts.mkdir(parents=True, exist_ok=True)
    out_wav = artifacts / f"{folder.name}.wav"
    trim_wav(mixdown, out_wav, seconds + tail)
    mixdown.unlink()
    report = audio_report.analyze(out_wav)
    report["song_seconds"] = round(seconds, 1)
    (artifacts / f"{folder.name}.json").write_text(json.dumps(report, indent=2))
    audio_report.write_png(out_wav, artifacts / f"{folder.name}.png")
    shutil.copy(log, artifacts / f"{folder.name}.log")
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", help="comma separated demo module names")
    parser.add_argument("--no-build", action="store_true")
    parser.add_argument("--artifacts", type=Path, default=ROOT / "sim-artifacts-demos")
    parser.add_argument("--audible", action="store_true", help="play the render through the speakers")
    parser.add_argument("--tail", type=float, default=3.0, help="seconds kept after one pass")
    args = parser.parse_args()

    if not args.no_build:
        build_sim()
    demos = lgpt_composer.load_demos()
    wanted = set(args.only.split(",")) if args.only else set(demos)
    last_project = PROJECTS / "last_project"
    saved_last = last_project.read_text() if last_project.exists() else None
    failures = []
    try:
        for name, module in demos.items():
            if name not in wanted:
                continue
            project = module.build()  # type: ignore[attr-defined]
            print(project.stats())
            report = render(name, project, args.artifacts, args.tail, args.audible)
            print(f"  peak {report['peak_db']} dB, rms {report['rms_db']} dB, clipped {report['clipped_ratio']:.4%}, "
                  f"silent {report['silent_seconds']}s, centroid {report['centroid_hz']} Hz")
            print(f"  bands {report['band_energy_db']}")
            if report["clipped_ratio"] > 0.001:
                failures.append(f"{name} clips")
    finally:
        if saved_last is None:
            last_project.unlink(missing_ok=True)
        else:
            last_project.write_text(saved_last)
    if failures:
        print("FAIL: " + ", ".join(failures), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
