#!/usr/bin/env python3
"""Build the demo songs, bounce them through the real app, and audit the audio.

For each tools/demos/*.py song this:
1. writes the lgpt_<Name> project (projects/resources/demos + simulator tracks)
2. points the simulator's last_project at it (AUTO_LOAD_LAST)
3. runs a generated headless script: Project -> Render: Stereo -> Start -> Stop
4. copies the app's own mixdown.wav into the artifacts folder, trimmed to one
   pass of the song, and writes an audio report (+ spectrogram PNG)
5. with --stems, bounces again in Stems mode and prints per-track levels

The simulator runs windowless and muted, so nothing steals focus or plays
through the speakers (use --audible to listen while it renders).

Usage:
    python tools/render_demos.py                 # all demos
    python tools/render_demos.py --only neon_drive --stems
    python tools/render_demos.py --no-build      # reuse the simulator build
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import wave
from pathlib import Path

import numpy as np

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
PROJECTS = ROOT / "projects"
SIM_TRACKS = ROOT / "rgnano-sim-data" / "tracks"
DEMO_OUT = PROJECTS / "resources" / "demos"
LOG = PROJECTS / "rgnano-sim.log"

# Never pop a console window (it would steal keyboard focus from the user)
NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)

sys.path.insert(0, str(TOOLS))
import audio_report  # noqa: E402
import lgpt_composer  # noqa: E402


def build_sim() -> None:
    subprocess.run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
                    str(TOOLS / "build-rgnano-sim.ps1")], cwd=ROOT, check=True,
                   creationflags=NO_WINDOW)


def trim_wav(src: Path, dst: Path, seconds: float) -> None:
    with wave.open(str(src), "rb") as r:
        params = r.getparams()
        frames = min(r.getnframes(), int(seconds * params.framerate))
        data = r.readframes(frames)
    with wave.open(str(dst), "wb") as w:
        w.setparams(params)
        w.writeframes(data)


def run_render(name: str, render_mode: int, wait_ms: int, audible: bool) -> int:
    """Project screen -> Render mode (1 Stereo, 2 Stems) -> Start -> wait -> Stop."""
    script = PROJECTS / "rgnano-sim-demo-render.rgsim"
    first_file = "mixdown.wav" if render_mode == 1 else "channel0.wav"
    script.write_text("\n".join([
        f"# generated by tools/render_demos.py for {name}",
        "wait 1500",
        "expect_view song",
        "route song.to_project",
        "expect_view project",
        f"sim_set_render_mode {render_mode}",
        "press s 80",
        f"wait {wait_ms}",
        "press s 80",
        "wait 600",
        f"expect_project_file_bytes {first_file} 1000",
        "sim_set_render_mode 0",
        "expect_no_error",
        "quit",
    ]) + "\n")
    res_dir = PROJECTS / "resources" / "RGNANO_SIM"
    shutil.copy(res_dir / "config.xml", PROJECTS / "config.xml")
    shutil.copy(res_dir / "mapping.xml", PROJECTS / "mapping.xml")
    env = os.environ.copy()
    env["PATH"] = "C:\\msys64\\mingw32\\bin;" + env.get("PATH", "")
    # Headless: hidden window, nothing on screen, no focus stealing
    cmd = [str(PROJECTS / "lgpt-rgnano-sim.exe"), f"-RGNANOSIM_SCRIPT={script}", f"-RGNANOSIM_LOG={LOG}",
           "-RGNANOSIM_HEADLESS=YES"]
    if not audible:
        cmd.append("-RGNANOSIM_MUTE=YES")
    proc = subprocess.run(cmd, creationflags=NO_WINDOW, cwd=ROOT, env=env, timeout=wait_ms / 1000 + 120)
    script.unlink(missing_ok=True)
    return proc.returncode


def stem_levels(sim_folder: Path, seconds: float) -> list[dict]:
    """Per-track peak and loud-section RMS from the app's own stem renders."""
    rows = []
    for ch in range(8):
        wav = sim_folder / f"channel{ch}.wav"
        if not wav.exists():
            continue
        data, rate = audio_report.read_wav(wav)
        data = data[: int(seconds * rate)]
        mono = data.mean(axis=1)
        win = rate // 2
        rms = [float(np.sqrt(np.mean(mono[i:i + win] ** 2))) for i in range(0, max(1, len(mono) - win), win)]
        active = sorted(r for r in rms if r > 1e-4)
        loud = active[int(len(active) * 0.9)] if active else 0.0
        peak = float(np.abs(data).max()) if data.size else 0.0
        rows.append({"track": ch, "peak_db": round(audio_report.db(peak), 1),
                     "loud_rms_db": round(audio_report.db(loud), 1),
                     "active_seconds": round(len(active) * 0.5, 1)})
        wav.unlink()
    return rows


def render(name: str, project: lgpt_composer.Project, artifacts: Path, tail: float,
           audible: bool = False, stems: bool = False) -> dict:
    folder = project.save(DEMO_OUT)
    sim_folder = SIM_TRACKS / folder.name
    if sim_folder.exists():
        shutil.rmtree(sim_folder)
    shutil.copytree(folder, sim_folder)
    mixdown = sim_folder / "mixdown.wav"

    (PROJECTS / "last_project").write_text(f"./rgnano-sim-data/tracks/{folder.name}")

    seconds = project.length_seconds()
    # Renders stream in real time: one full pass plus the tail, extra is trimmed
    wait_ms = int(seconds * 1000 + tail * 1000 + 1500)
    code = run_render(name, 1, wait_ms, audible)
    if code != 0 or not mixdown.exists():
        raise RuntimeError(f"{name}: render failed (exit {code}); see {LOG}")

    artifacts.mkdir(parents=True, exist_ok=True)
    out_wav = artifacts / f"{folder.name}.wav"
    trim_wav(mixdown, out_wav, seconds + tail)
    mixdown.unlink()
    report = audio_report.analyze(out_wav)
    report["song_seconds"] = round(seconds, 1)
    audio_report.write_png(out_wav, artifacts / f"{folder.name}.png")
    shutil.copy(LOG, artifacts / f"{folder.name}.log")

    if stems:
        code = run_render(name, 2, wait_ms, audible)
        if code != 0:
            raise RuntimeError(f"{name}: stem render failed (exit {code}); see {LOG}")
        report["stems"] = stem_levels(sim_folder, seconds)
    (artifacts / f"{folder.name}.json").write_text(json.dumps(report, indent=2))
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", help="comma separated demo module names")
    parser.add_argument("--no-build", action="store_true")
    parser.add_argument("--artifacts", type=Path, default=ROOT / "sim-artifacts-demos")
    parser.add_argument("--audible", action="store_true", help="play the render through the speakers")
    parser.add_argument("--stems", action="store_true", help="also bounce per-track stems and print levels")
    parser.add_argument("--tail", type=float, default=3.0, help="seconds kept after one pass")
    args = parser.parse_args()

    if not args.no_build:
        build_sim()
    demos = lgpt_composer.load_demos()
    wanted = set(args.only.split(",")) if args.only else set(demos)
    last_project = PROJECTS / "last_project"
    saved_last = last_project.read_text() if last_project.exists() else None
    failures = []
    try:
        for name, module in demos.items():
            if name not in wanted:
                continue
            project = module.build()  # type: ignore[attr-defined]
            print(project.stats(), flush=True)
            report = render(name, project, args.artifacts, args.tail, args.audible, args.stems)
            print(f"  peak {report['peak_db']} dB, rms {report['rms_db']} dB, crest {report['crest_db']} dB, "
                  f"clipped {report['clipped_ratio']:.4%}, silent {report['silent_seconds']}s", flush=True)
            print(f"  bands {report['band_energy_db']}", flush=True)
            for st in report.get("stems", []):
                print(f"  track {st['track']}: peak {st['peak_db']:6.1f} dB  loud rms {st['loud_rms_db']:6.1f} dB  "
                      f"active {st['active_seconds']}s", flush=True)
            if report["clipped_ratio"] > 0.001:
                failures.append(f"{name} clips")
    finally:
        if saved_last is None:
            last_project.unlink(missing_ok=True)
        else:
            last_project.write_text(saved_last)
    if failures:
        print("FAIL: " + ", ".join(failures), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
